# Minimal config. version is the only required field.
version = 1

[merge]
# If there is a merge conflict, make a comment on the PR and remove the
# automerge label. This option only applies when `merge.require_automerge_label`
# is enabled.
notify_on_conflict = false # default: true
